// ignore_for_file: constant_identifier_names

const INTENT_PHONE = "INTENT_PHONE";
const INTENT_FROM = "INTENT_FROM";
const INTENT_FROM_FORGOT_PASSWORD = "INTENT_FROM_FORGOT_PASSWORD";
const INTENT_FROM_SIGN_UP = "INTENT_FROM_SIGN_UP";

const INTENT_SERVICE_ID = "INTENT_SERVICE_ID";

const INTENT_ADDRESS = "INTENT_ADDRESS";
const INTENT_LANG = "INTENT_LANG";
const INTENT_LAT = "INTENT_LAT";

const INTENT_APPOINTMENT_DATE_TIME = "INTENT_APPOINTMENT_DATE_TIME";
const INTENT_APPOINTMENT_ID = "INTENT_APPOINTMENT_ID";

const INTENT_FROM_SERVICES = "INTENT_FROM_SERVICES";
const INTENT_FROM_HOMECARE = "INTENT_FROM_HOMECARE";
const HOMECARE = "homecare";
const APPOINTMENT = "appointment";

const INTENT_PHONE_CODE = "INTENT_PHONE_CODE";

const INTENT_CMS_PAGE = "INTENT_CMS_PAGE";
const INTENT_TERMS_CONDITION = "INTENT_TERMS_CONDITION";
const INTENT_PRIVACY_POLICY = "INTENT_PRIVACY_POLICY";
const INTENT_COOKIES_POLICY = "INTENT_COOKIES_POLICY";

const INTENT_FROM_LOGIN = "INTENT_FROM_LOGIN";

const INTENT_CONSENT_FILE = "INTENT_CONSENT_FILE";
const INTENT_FROM_MY_LIST = "INTENT_FROM_MY_LIST";
const INTENT_FROM_REGISTER = "INTENT_FROM_REGISTER";
