// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf7U0OwVzFNRyvXBYf3eTh-GqBZMuSzp4',
    appId: '1:750176798764:web:b6e795a8241447bedd6989',
    messagingSenderId: '750176798764',
    projectId: 'smarthealthapp-c787e',
    storageBucket: 'smarthealthapp-c787e.appspot.com',
    authDomain: 'smarthealthapp-c787e.firebaseapp.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf7U0OwVzFNRyvXBYf3eTh-GqBZMuSzp4',
    appId: '1:750176798764:android:b6e795a8241447bedd6989',
    messagingSenderId: '750176798764',
    projectId: 'smarthealthapp-c787e',
    storageBucket: 'smarthealthapp-c787e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC96Iuwy3Se6vTFUSBZOijV3yqJ3PzZieU',
    appId: '1:750176798764:ios:4e3fc39de6cdef46dd6989',
    messagingSenderId: '750176798764',
    projectId: 'smarthealthapp-c787e',
    storageBucket: 'smarthealthapp-c787e.appspot.com',
    androidClientId:
        '750176798764-57fjpgd6n186a87qqg1d882c2l5j82lg.apps.googleusercontent.com',
    iosClientId:
        '750176798764-ivufn2m4g317smrgcplpg0pvt9a2ood9.apps.googleusercontent.com',
    iosBundleId: 'com.smarthelath.hcp',
  );
}
